version: "3"

services:

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config_files/nginx/config/default:/etc/nginx/conf.d/default.conf:ro
    networks:
      - webnet
    depends_on:
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
    volumes:
      - ./config_files/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - webnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    volumes:
      - ./config_files/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - webnet

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    ports:
      - ":"
    volumes:
      - ./config_files/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config_files/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      #- ./logstash/pattern/nginx_access:/usr/share/logstash/conf/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
