version: "3"

services:

  volumes:
    shared_folder:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: ./config_files

  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - shared_folder/nginx/config/default:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    ports:
    volumes:
      - shared_folder/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    volumes:
      - shared_folder/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.1
    ports:
      - ":"
    volumes:
      - shared_folder/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - shared_folder/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      #- ./logstash/pattern/nginx_access:/usr/share/logstash/conf/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
